%This script allows you to select multiple ROIs from a video, calculate
%deltaF/F for each ROI, and plot the deltaF/F traces against a temperature
%ramp
%Incorporates deltaF/F calculations from Jenna Sternberg and
%Claire Wyart's lab
%Plots generated by this script are not used for publication, just
%for visualizing the traces you're measuring

clear all; close all

disp ('Choose image acquisition file')
[image folder] = uigetfile('*.*');
imagefile = strcat(folder, image);

disp ('Choose image to select ROIs')
[file2, folder2]= uigetfile('*.*');
StanDev = strcat(folder2, file2);

nframes = input('How many frames is the image file? ');
freq = input('What is the frequency of acquisition in Hz? ');
maxintensity = input('Choose maximum pixel intensity for display');
ROI_choice_frame = input('Choose frame to pick ROIs');
start_temp = input('Temp ramp lower limit?');
end_temp = input('Temp ramp upper limit?');

M=multitiff2M_16bit(imagefile,1:nframes);
% Mr = registerfilm_ROI(M(:,:,1:nframes),1);
% flattenM = mean(M,3); 
x_dim = length(M(1,:,1));
y_dim = length(M(:,1,1));

figure;I=imread(StanDev,ROI_choice_frame);imshow(I,[0,maxintensity]);set(gcf, 'Position', get(0, 'Screensize'));
disp('Choose left set of ROIs')
% call function getROIcell which allows user to select ROIs
rois = getROIcell;
close all
    
% generate mask from rois, calculate dff
if isempty(rois);
    dff = []
    raw = []
    Mask = []
    int = [];
end

for i=1:size(rois,2); 
    Mask{i} = roipoly(imread(imagefile),rois{i}(:,1),rois{i}(:,2));
end;

%function calc_dff_NH calculates delta F/F for chosen ROIs
[dff, raw] = calc_dff_NH(M, Mask, size(rois,2));

%top100 pixels version
%[dff, final] = calc_dff_NH_top100(M, Mask, size(rois,2));

%backgroundsub version:
%[dff_v, raw_v] = calc_dffNH_with_background_subtraction(M, Mask_v, size(rois_v,2));

% Generate png/fig for mask of rois
figure; imshow(I,[0,maxintensity]);
for i=1:length(rois);
    patch(rois{1,i}(:,1),rois{1,i}(:,2),'m','FaceAlpha',0.3);
    text(rois{1,i}(1,1),rois{1,i}(1,2),num2str(i),'Color','g');
    hold on;
end

title('ROIs','FontSize', 18);
rois = strcat(folder, 'ROIs');
saveas(gcf, rois,'fig'); 
saveas(gcf, rois,'png');
close

%need this for Harry's script
mypath = fullfile(folder);
fname = image;


accuthermo_file = readtable(strcat(mypath,fname(1:end-3),'dat'));

Temperat = table2array(accuthermo_file(11:size(accuthermo_file),4));

Good_IND = [1:length(dff)];
Temperature = interp1(1:length(Temperat),Temperat,Good_IND);

Image_Time = length(dff);
resampletemp = Temperature;
pathname = mypath;

%interpolated temperature trace for "real" temperature (input at start of script) 
%rather than innacurately measured accuthermo temperature
real_temp = interp1([21 length(dff)],[start_temp end_temp],(21:length(dff)));
base_temp = start_temp*ones(1,20);
real_temp_ramp = [base_temp,real_temp];

average_trace = mean(dff,2);

figure('position', [1200 0 700 1000]); hold on;
for i=1:size(dff,2)
    
    %subplot(size(rois,2),1,i);
    yyaxis left; ylim([min(dff(:)), (max(dff(:)))]); F_trace = plot(dff(:,i),'-k'); F_trace.Color(4)=0.3;
    plot(average_trace,'-k','LineWidth',2);
    ylabel('\deltaF/F (%)');
    yyaxis right; ylim([(min(Temperature)-1), (max(Temperature)+1)]); 
    plot(Temperat,'-g');
    %or use this for average-
    %yyaxis right; ylim([(min(average_T)-1), (max(average_T)+1)]); 
    %plot(average_T,'-g','LineWidth',2);
    ylabel('Temperature');
end

delta_F = strcat(folder, 'delta_F');
saveas(gcf, delta_F,'fig');

pause(5);
close

figure('position', [1200 0 700 1000]); hold on;

%subplot(size(rois,2),1,i);
yyaxis left; ylim([min(dff(:)), (max(dff(:)))]); F_trace = plot(dff,'-k'); %F_trace.Color(4)=0.3;
%F2_trace = plot(dff(:,2),'-r'); F2_trace.Color(4)=0.3;
%plot(average_trace,'-k','LineWidth',2);
plot(average_trace,'-k','LineWidth',2);
ylabel('\deltaF/F (%)');
yyaxis right; ylim([(min(real_temp_ramp)-1), (max(real_temp_ramp)+1)]); 
plot(real_temp_ramp,'-g','LineWidth',2);
%or use this for average-
%yyaxis right; ylim([(min(average_T)-1), (max(average_T)+1)]); 
%plot(average_T,'-g','LineWidth',2);
ylabel('Temperature');


delta_F_real = strcat(folder, 'delta_F_real');
saveas(gcf, delta_F_real,'fig');

pause(5);
close

save analysis

